version = 1

[[annotations]]
path = [
    "REUSE.toml",
    "crowdin.yml",
    "CMakeSettings.json",
    "CMakeDarwinPresets.json",
    "CMakeLinuxPresets.json",
    "CMakeWindowsPresets.json",
    "CMakePresets.json",
    ".github/FUNDING.yml",
    ".github/shadps4.png",
    ".github/workflows/scripts/update_translation.sh",
    ".github/workflows/update_translation.yml",
    ".gitmodules",
    "dist/MacOSBundleInfo.plist.in",
    "dist/net.shadps4.shadPS4.desktop",
    "dist/net.shadps4.shadPS4_metadata.pot",
    "dist/net.shadps4.shadPS4.metainfo.xml",
    "dist/qt.conf",
    "documents/changelog.md",
    "documents/Quickstart/2.png",
    "documents/Screenshots/*",
    "documents/Screenshots/Linux/*",
    "externals/MoltenVK/MoltenVK_icd.json",
    "scripts/ps4_names.txt",
    "src/images/bronze.png",
    "src/images/gold.png",
    "src/images/platinum.png",
    "src/images/silver.png",
    "src/images/about_icon.png",
    "src/images/controller_icon.png",
    "src/images/discord.png",
    "src/images/dump_icon.png",
    "src/images/exit_icon.png",
    "src/images/favorite_icon.png",
    "src/images/trophy_icon.png",
    "src/images/flag_china.png",
    "src/images/flag_eu.png",
    "src/images/flag_jp.png",
    "src/images/flag_unk.png",
    "src/images/flag_us.png",
    "src/images/flag_world.png",
    "src/images/folder_icon.png",
    "src/images/github.png",
    "src/images/grid_icon.png",
    "src/images/keyboard_icon.png",
    "src/images/usb_icon.png",
    "src/images/iconsize_icon.png",
    "src/images/KBM.png",
    "src/images/ko-fi.png",
    "src/images/list_icon.png",
    "src/images/list_mode_icon.png",
    "src/images/pause_icon.png",
    "src/images/play_icon.png",
    "src/images/ps4_controller.png",
    "src/images/restart_game_icon.png",
    "src/images/refreshlist_icon.png",
    "src/images/settings_icon.png",
    "src/images/fullscreen_icon.png",
    "src/images/stop_icon.png",
    "src/images/utils_icon.png",
    "src/images/shadPS4.icns",
    "src/images/shadps4.ico",
    "src/images/shadps4.png",
    "src/images/net.shadps4.shadPS4.svg",
    "src/images/themes_icon.png",
    "src/images/update_icon.png",
    "src/images/youtube.png",
    "src/images/website.png",
    "src/images/discord.svg",
    "src/images/github.svg",
    "src/images/ko-fi.svg",
    "src/images/shadps4.svg",
    "src/images/website.svg",
    "src/images/youtube.svg",
    "src/images/trophy.wav",
    "src/images/hotkey.png",
    "src/images/game_settings.png",
    "src/shadps4.qrc",
    "src/shadps4.rc",
    "src/qt_gui/translations/update_translation.sh",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "shadPS4 Emulator Project"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "externals/cmake-modules/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2010 Iowa State University"
SPDX-License-Identifier = "BSL-1.0"

[[annotations]]
path = "cmake/CMakeRC.cmake"
SPDX-FileCopyrightText = "Copyright (c) 2017 vector-of-bool <vectorofbool@gmail.com>"
SPDX-License-Identifier = "MIT"
